/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Modul5Lanjutan;

/**
 *
 * @author rismaintanw
 */
public class lanjutan extends javax.swing.JFrame {

    /**
     * Creates new form lanjutan
     */
    public lanjutan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Nama = new javax.swing.JTextField();
        Absen = new javax.swing.JTextField();
        Alamat = new javax.swing.JTextField();
        Kelas = new javax.swing.JComboBox<>();
        rdb1 = new javax.swing.JRadioButton();
        rdb2 = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(170, 10, 34, 14);

        jLabel2.setText("Nama");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 50, 50, 14);

        jLabel3.setText("Absen");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 80, 60, 14);

        jLabel4.setText("Kelas");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 110, 60, 14);

        jLabel5.setText("Jurusan");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 140, 50, 14);

        jLabel6.setText("Alamat");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(30, 170, 33, 14);
        getContentPane().add(Nama);
        Nama.setBounds(110, 50, 100, 20);
        getContentPane().add(Absen);
        Absen.setBounds(110, 80, 100, 20);
        getContentPane().add(Alamat);
        Alamat.setBounds(110, 170, 100, 20);

        Kelas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "XI RPL1", "XI RPL2", "XI RPL3", "XI RPL4", "XIRPL5", "XI RPL6", "XI TKJ1", "XI TKJ 2", "XI TKJ 3", "XI TKJ 4", "XI TKJ 5", "XI TKJ 6" }));
        Kelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KelasActionPerformed(evt);
            }
        });
        getContentPane().add(Kelas);
        Kelas.setBounds(110, 110, 100, 20);

        rdb1.setText("RPL");
        rdb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdb1ActionPerformed(evt);
            }
        });
        getContentPane().add(rdb1);
        rdb1.setBounds(110, 140, 43, 23);

        rdb2.setText("TKJ");
        getContentPane().add(rdb2);
        rdb2.setBounds(180, 140, 93, 23);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Modul5Lanjutan/1.11.jpeg"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(270, 10, 330, 180);

        jButton1.setText("SEND");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(70, 230, 59, 23);

        jButton2.setText("EXIT");
        getContentPane().add(jButton2);
        jButton2.setBounds(180, 230, 55, 23);

        setBounds(0, 0, 701, 339);
    }// </editor-fold>//GEN-END:initComponents

    private void KelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KelasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_KelasActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    String nama=Nama.getText();
    String absen=Absen.getText();
    String kelas=Kelas.getSelectedItem().toString();
    String jurusan="";
    String alamat=Alamat.getText();
    if (rdb1.isSelected())
        jurusan="RPL";
    if(rdb2.isSelected())
        jurusan="TKJ";
    else
    
    if(Kelas.getSelectedItem()=="XI RPL 1"){}
    if(Kelas.getSelectedItem()=="XI RPL 2"){}
    if(Kelas.getSelectedItem()=="XI RPL 3"){}
    if(Kelas.getSelectedItem()=="XI RPL 4"){}
    if(Kelas.getSelectedItem()=="XI RPL 5"){}
    if(Kelas.getSelectedItem()=="XI RPL 6"){}
    if(Kelas.getSelectedItem()=="XI TKJ 1"){}
    if(Kelas.getSelectedItem()=="XI TKJ 2"){}
    if(Kelas.getSelectedItem()=="XI TKJ 3"){}
    if(Kelas.getSelectedItem()=="XI TKJ 4"){}
    if(Kelas.getSelectedItem()=="XI TKJ 5"){}
    if(Kelas.getSelectedItem()=="XI TKJ 6"){}
    
    new frame2(nama, absen, kelas, jurusan, alamat).setVisible(true);
    // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void rdb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdb1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdb1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(lanjutan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(lanjutan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(lanjutan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(lanjutan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new lanjutan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Absen;
    private javax.swing.JTextField Alamat;
    private javax.swing.JComboBox<String> Kelas;
    private javax.swing.JTextField Nama;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JRadioButton rdb1;
    private javax.swing.JRadioButton rdb2;
    // End of variables declaration//GEN-END:variables
}
